### PR TITLE
The Big Scaffolding Adoption, part 6: packaging

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/changelog` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_h_Y14zZEp0ibfziO:-Nr_h_Y14zZEp0ibfziP:b297h01) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/changelog#L4)):*
> ```
> 
>   * First official (numbered) release.
>   * Requires gramine 1.6.
> ```

`Gramine` (capital letter)
___
*[`debian/control` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hhjr8vn0Tv3RKgEC:-Nr_hhjr8vn0Tv3RKgED:bbwwol0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/control#L25)):*
> ```
> Architecture: amd64
> Description: framework for quick development of Gramine apps
>  TBD
> ```

Do you want to add some description now?
___
*[`debian/copyright` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hrSODGRm5p0yredF:-Nr_hrSODGRm5p0yredG:b-177h5t) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/copyright#L3)):*
> ```
> Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
> Upstream-Name: gramine-scaffolding
> Upstream-Contact: Invisible Things Lab <contact@invisiblethingslab.com>
> ```

Is this a correct email? And generally a correct contact?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)* status: 11 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/changelog` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_h_Y14zZEp0ibfziO:-Nrf6DiRE7x0kY7DahAv:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/changelog#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Gramine` (capital letter)
</blockquote></details>

Done.
___
*[`debian/control` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hhjr8vn0Tv3RKgEC:-Nrf6txl8wbILtDMmUTP:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/control#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you want to add some description now?
</blockquote></details>

Done.
___
*[`debian/copyright` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hrSODGRm5p0yredF:-Nrf71vb9-MPPUSKabSg:b-lpnhmb) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/copyright#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a correct email? And generally a correct contact?
</blockquote></details>

It is: https://invisiblethingslab.com/#contact

If you don't want ITL, I can substitute my own, or something else.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/copyright` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hrSODGRm5p0yredF:-Nribfcq96B2PqLD_VrG:b-mpj5oi) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/copyright#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It is: https://invisiblethingslab.com/#contact

If you don't want ITL, I can substitute my own, or something else.
</blockquote></details>

Did you discuss with whoever is the Intel contact which email is preferred? For me personally it doesn't matter, but this is the first time we mention this email, so want to be sure that's fine.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/copyright` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hrSODGRm5p0yredF:-NroiGAQ4J2GUDaGU6Fw:b-o0xto1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/copyright#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you discuss with whoever is the Intel contact which email is preferred? For me personally it doesn't matter, but this is the first time we mention this email, so want to be sure that's fine.
</blockquote></details>

It was approved in the initial project together with the rest of the project.

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`debian/copyright` line 3 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/7#-Nr_hrSODGRm5p0yredF:-NsrhEV_6krFp4oLyUYP:bzgvnu1) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/b8f92508d92cc0f40f55c9b52ca37f8338b03121/debian/copyright#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It was approved in the initial project together with the rest of the project.
</blockquote></details>

Ok, resolving then

**Pull request merged**
