### PR TITLE
Release 1.7

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)

### CODE REVIEW

**Review by oshogbo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-:-NvkjJaA887sCdVDybiq:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`pyproject.toml` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-NvkzfWjCu8c4zZaAR65:-NvkzfWkBXVjk6buCMeU:bbpj8ww) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/e76cdfcbb0125c00a75698e992824518579e523d/pyproject.toml#L7)):*
> ```TOML
> [project]
> name = "graminescaffolding"
> version = "1.7.post0"
> ```

Why not `~UNRELEASED` as you do in core Gramine?
___
*[`graminescaffolding/__init__.py` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-NvkzlfA-7cZsN_nthsf:-NvkzlfA-7cZsN_nthsg:b-7ropln) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/e76cdfcbb0125c00a75698e992824518579e523d/graminescaffolding/__init__.py#L5)):*
> ```Python
> #                    Wojtek Porczyk <woju@invisiblethingslab.com>
> 
> __version__ = "1.7.post0"
> ```

ditto

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)* status: 3 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`pyproject.toml` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-NvkzfWjCu8c4zZaAR65:-NvqD940AVqe6s9VheVL:b-f2cs07) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/e76cdfcbb0125c00a75698e992824518579e523d/pyproject.toml#L7)):*
Because you can't have arbitrary strings as part of python (strict) version:
https://packaging.python.org/en/latest/specifications/version-specifiers/
There is a limited set of allowed suffixes, `a` for alpha, `b` for beta, `rc` for release candidate, `.post` and `.dev` (note dots) for devel versions. They all carry a decimal number and nothing else.

We already have a similar problem with alpine that also has limitation in version syntax, but we can work around that problem, because `APKBUILD` is a shell script, so I place real version in a variable and `sed` it. I reasonably could have worked that around in `__init__.py` (which is also executable), but not in `pyproject.toml` (which is declarative).

```
% python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version
>>> Version('1.7.post0')
<Version('1.7.post0')>
>>> Version('1.7.post~UNRELEASED')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '1.7.post~UNRELEASED'
```

I have an adapter for that in another version of `release.sh` script (gramineproject/gramine#), which I have not yet pushed.
___
*[`graminescaffolding/__init__.py` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-NvkzlfA-7cZsN_nthsf:-NvqFcuk5oWkdkDugRv-:b-7ropln) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/e76cdfcbb0125c00a75698e992824518579e523d/graminescaffolding/__init__.py#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)* status: 3 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`pyproject.toml` line 7 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12#-NvkzfWjCu8c4zZaAR65:-NvqJNz187D8UDSbscgQ:bo9bbg0) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/e76cdfcbb0125c00a75698e992824518579e523d/pyproject.toml#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because you can't have arbitrary strings as part of python (strict) version:
https://packaging.python.org/en/latest/specifications/version-specifiers/
There is a limited set of allowed suffixes, `a` for alpha, `b` for beta, `rc` for release candidate, `.post` and `.dev` (note dots) for devel versions. They all carry a decimal number and nothing else.

We already have a similar problem with alpine that also has limitation in version syntax, but we can work around that problem, because `APKBUILD` is a shell script, so I place real version in a variable and `sed` it. I reasonably could have worked that around in `__init__.py` (which is also executable), but not in `pyproject.toml` (which is declarative).

```
% python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version
>>> Version('1.7.post0')
<Version('1.7.post0')>
>>> Version('1.7.post~UNRELEASED')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '1.7.post~UNRELEASED'
```

I have an adapter for that in another version of `release.sh` script (gramineproject/gramine#), which I have not yet pushed.
</blockquote></details>

gramineproject/gramine#1788 was that missing link

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/12)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
