### PR TITLE
Fix building docs on RTD

### PR DESCRIPTION
**Pull request by woju**
## Description of the changes 
Added missing config (`requirements.txt`) that RTD needs.
## How to test this PR? 

See checks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
nitpick: I'd prefer "Docs:" or "[Docs]", "Documentation:" will age very poorly with any non-trivial commit message one-liners.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: I'd prefer "Docs:" or "[Docs]", "Documentation:" will age very poorly with any non-trivial commit message one-liners.
</blockquote></details>

This matches directory name. If you insist, I'll rename the directory (it's not set in stone...).

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv, @kailun-qin, and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This matches directory name. If you insist, I'll rename the directory (it's not set in stone...).
</blockquote></details>

In Gramine we tag by component names, which don't correspond 1-1 to top-level directories, which is IMO fine, because we can be more concise with the tags (e.g. we write `[Docs]` instead of `Documentation:` and `PAL/Linux-SGX` instead of `pal/src/host/linux-sgx`). I won't die on this hill, but I prefer Gramine's convention, because the space in the one-liner is super limited and we save some space for a better commit contents description this way.

@kailun-qin, @dimakuv, @oshogbo: Any preferences here?

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv and @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
> In Gramine we tag by component names, which don't correspond 1-1 to top-level directories, which is IMO fine

> I prefer Gramine's convention, because the space in the one-liner is super limited and we save some space for a better commit contents description this way.

+1, I like the current convention (i.e., `[Docs]` and we recommanded this way).

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

> In Gramine we tag by component names, which don't correspond 1-1 to top-level directories, which is IMO fine

> I prefer Gramine's convention, because the space in the one-liner is super limited and we save some space for a better commit contents description this way.

+1, I like the current convention (i.e., `[Docs]` and we recommanded this way).
</blockquote></details>

I like `[Docs]` too. Also, we've been using it for ages, so I prefer consistency/uniformity other directory-matching.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11#-NtE3tD18N7sGsYXbFB4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like `[Docs]` too. Also, we've been using it for ages, so I prefer consistency/uniformity other directory-matching.
</blockquote></details>

OK, fixed.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/11)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
