### PR TITLE
The Big Scaffolding Adoption, part 5: CI and linters

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.zuul.d/jobs.yaml` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_hEgfCXncxJqsaTgK:-Nr_hEgfCXncxJqsaTgL:bxsaul9) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/jobs.yaml#L41)):*
> ```YAML
> - job:
>     name: scaffolding-tests
>     nodeset: any
> ```

You don't run these with SGX? Why not? How can you be sure that SGX versions of Scaffolding projects indeed work then?
___
*[`.zuul.d/playbooks/scaffolding-tests/run.yaml` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_ghTP0_JUHGLslPds:-Nr_ghTP0_JUHGLslPdt:by833ls) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/playbooks/scaffolding-tests/run.yaml#L24)):*
> ```YAML
> 
>     - name: Run hadolint
>       command: ./run-hadolint --ignore DL3008 --ignore DL3009 --ignore DL3059 --ignore DL3006
> ```

Any explanations why we instruct Hadolint to ignore these particular issues?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`.zuul.d/jobs.yaml` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_hEgfCXncxJqsaTgK:-Nrf9S6T4VwD_RjkO6Tp:b-8vze3x) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/jobs.yaml#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't run these with SGX? Why not? How can you be sure that SGX versions of Scaffolding projects indeed work then?
</blockquote></details>

Because currently all nodes are SGX (total amount of 1 box...). This will need to be adjusted when we finally deploy zuul in Gramine.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.zuul.d/jobs.yaml` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_hEgfCXncxJqsaTgK:-NribTZW57oju04h5idK:be58bf9) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/jobs.yaml#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because currently all nodes are SGX (total amount of 1 box...). This will need to be adjusted when we finally deploy zuul in Gramine.
</blockquote></details>

Why not fix `any` to `sgx` here right now?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.zuul.d/playbooks/scaffolding-tests/run.yaml` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_ghTP0_JUHGLslPds:-NrjBlVx9NnVBU1gnPWB:bagpuj4) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/playbooks/scaffolding-tests/run.yaml#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any explanations why we instruct Hadolint to ignore these particular issues?
</blockquote></details>

# DL3008
https://github.com/codacy/codacy-hadolint/blob/master/codacy-hadolint/docs/description/DL3008.md
We don't pin versions.

# DL3009
Actually, this one can be dropped IMHO. Because the last change has introduced the `apt_install` macro, we clean the cache after each installation (@woju).

# DL3059
The intermediate Dockerfile uses a couple of `RUN` statements next to each other because they are spread between different sections of templates. This doesn't matter because at the end, we squash all the layers.

# DL3006
We are using construct `FROM ${ARG}`; hadolint requires `FROM static version`; however, as we use multiple Dockerfiles, we can't achieve that.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`.zuul.d/playbooks/scaffolding-tests/run.yaml` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_ghTP0_JUHGLslPds:-NrjOcnC-VU8Z0Emz_0a:brhx2oi) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/playbooks/scaffolding-tests/run.yaml#L24)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

# DL3008
https://github.com/codacy/codacy-hadolint/blob/master/codacy-hadolint/docs/description/DL3008.md
We don't pin versions.

# DL3009
Actually, this one can be dropped IMHO. Because the last change has introduced the `apt_install` macro, we clean the cache after each installation (@woju).

# DL3059
The intermediate Dockerfile uses a couple of `RUN` statements next to each other because they are spread between different sections of templates. This doesn't matter because at the end, we squash all the layers.

# DL3006
We are using construct `FROM ${ARG}`; hadolint requires `FROM static version`; however, as we use multiple Dockerfiles, we can't achieve that.
</blockquote></details>

Thanks. Can we remove `DL3009` then? Others we can keep.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: 9 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`.zuul.d/jobs.yaml` line 41 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_hEgfCXncxJqsaTgK:-NroDHX39qKLcFmd66Bt:b-ccpdck) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/jobs.yaml#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not fix `any` to `sgx` here right now?
</blockquote></details>

Because it won't be `sgx` either, it will be some specific distro (possibly debian 12 or ubuntu 24.04, which is not released yet). I simply don't know until I set up zuul for `gramineproject`.
___
*[`.zuul.d/playbooks/scaffolding-tests/run.yaml` line 24 at r1](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6#-Nr_ghTP0_JUHGLslPds:-NroFRee0u0AU4Xrbc7-:b-896fix) ([raw file](https://github.com/gramineproject/gramine-scaffolding/blob/05fd6bf96a4a32ecbd55a2a95171e77f447caca8/.zuul.d/playbooks/scaffolding-tests/run.yaml#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks. Can we remove `DL3009` then? Others we can keep.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine-scaffolding/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
